---
# tasks
- name: install package rhel
  yum:
    name: openssh-server
    state: present
  when: (ansible_os_family == "RedHat" and ansible_pkg_mgr == "yum")

- name: install package ubuntu
  apt:
    name: openssh-server
    state: present
  when: (ansible_os_family == "Ubuntu" and ansible_pkg_mgr == "apt")

- name: install package debian
  apt:
    name: openssh-server
    state: present
  when: (ansible_os_family == "Debian" and ansible_pkg_mgr == "apt")
