---
# tasks
- name: install package rhel
  yum:
    name: vi
    state: present
  when: (ansible_pkg_mgr == "yum")

- name: install package ubuntu/debian
  apt:
    name: vi
    state: present
  when: (ansible_pkg_mgr == "apt")

