---
# tasks
- name: install package rhel
  yum:
    name: vim
    state: present
  when: (ansible_os_family == "RedHat" and ansible_pkg_mgr == "yum")

- name: install package ubuntu
  apt:
    name: vim
    state: present
  when: (ansible_os_family == "Ubuntu")

- name: install package debian
  apt:
    name: vim
    state: present
  when: (ansible_os_family == "Debian")
